local const = require("poste-db.constants")

describe("constants helpers", function()
  it("detects section markers", function()
    assert.is_true(const.is_section_marker("###"))
    assert.is_true(const.is_section_marker("   ### refresh"))
    assert.is_false(const.is_section_marker("-- @connection foo"))
  end)

  it("matches directive values", function()
    assert.equals("analytics", const.match_directive("-- @connection analytics", const.DIRECTIVE_CONNECTION))
    assert.equals("blog", const.match_directive("  -- @database blog", const.DIRECTIVE_DATABASE))
    assert.is_nil(const.match_directive("###", const.DIRECTIVE_CONNECTION))
  end)

  it("exposes shared numeric defaults", function()
    assert.equals(0.7, const.FLOAT_WIDTH_RATIO)
    assert.equals(120, const.FLOAT_MAX_WIDTH)
    assert.equals(5000, const.EDIT_MAX_ROWS)
    assert.equals(1000, const.LOG_MAX_ENTRIES)
    assert.equals(50, const.YANK_PREVIEW_CHARS)
  end)
end)
