--- The dataset edit commit's journal entry. A commit whose statements all ran
--- but matched fewer rows than there were edits is a PARTIAL outcome: the WARN
--- notification scrolls away, so the journal has to carry both the fact and
--- the reason, or `<leader>l` claims every edit landed.

local sql_log = require("poste-db.sql_log")

local captured = {}
local notices = {}
-- Declared before `journal_entries` reads it: a local declared after a
-- function body resolves as a nil global inside that body (AGENTS.md).
local log_path

local function commit_body(results, extra)
  local body = { type = "affected", results = results }
  for k, v in pairs(extra or {}) do body[k] = v end
  return body
end

--- 2 updates are generated by the dml stub, so "expected rows" is 2.
local function two_updates()
  return {
    { type = "update", sql = "UPDATE tb SET name = 'a' WHERE id = 1" },
    { type = "update", sql = "UPDATE tb SET name = 'b' WHERE id = 2" },
  }
end

local function install_stubs(body)
  package.loaded["poste-db.state"] = {
    context = { connection = nil, database = nil },
    find_poste_binary = function() return "/tmp/poste" end,
    log = function() end,
  }
  package.loaded["poste-db.editor"] = {
    clear_pk_cache = function() end,
    reset_edit_state = function() end,
  }
  package.loaded["poste-db.editor.column"] = { ensure_primary_key = function() end }
  package.loaded["poste-db.sql_runner"] = { get_exec_seq = function() return 1 end }
  package.loaded["poste-db.connections"] = {
    resolve_connection_url = function(name) return "mysql://" .. name, nil end,
    get_connection_config = function() return nil end,
  }
  package.loaded["poste-db.statement"] = { extract_table_name = function() return "tb" end }
  package.loaded["poste-db.dml"] = { generate_dml = two_updates }
  package.loaded["poste-db.format"] = {
    format_dataset = function() return { "│ id │" }, { type = "resultset" }, nil end,
  }
  package.loaded["poste-db.buffer"] = { render_dataset = function() end }
  captured.dispatches = {}
  package.loaded["poste-db.exec_run"] = {
    run_async = function(sql, opts, callbacks)
      captured.dispatches[#captured.dispatches + 1] = { sql = sql, opts = opts }
      -- Only the commit itself gets a response; the follow-up dataset refresh
      -- would otherwise re-enter this callback from inside the callback.
      if #captured.dispatches == 1 and callbacks.on_response then
        callbacks.on_response({
          status = body.has_error and "error" or "ok",
          latency_ms = 3,
          body = vim.json.encode(body),
          has_error = body.has_error == true,
          results = body.results,
        })
      end
      return 7
    end,
  }
  -- edit_commit binds dml/buffer/editor as module-level locals at require
  -- time, so the stubs above only land if the cached module is dropped.
  package.loaded["poste-db.edit_commit"] = nil
end

local function dirty_tab()
  local D = require("poste-db.dataset")
  D.tabs = { {
    original_sql = "SELECT * FROM tb;",
    src_file = "test.sql",
    src_buf = 7,
    layout = { dialect = "mysql", columns = {}, table_name = "tb", _conn_name = "dev" },
    edit_state = {
      dirty = true,
      modified_cells = { ["1:2"] = { col = 2, value = "a" }, ["2:2"] = { col = 2, value = "b" } },
      deleted_rows = {},
      added_rows = {},
      cell_errors = {},
    },
  } }
  D.active_tab_idx = 1
end

local function clear_tabs()
  local D = require("poste-db.dataset")
  D.tabs = {}
  D.active_tab_idx = 0
end

--- Entries actually written to the journal file (the writer's output is the
--- contract — a field dropped by `format_entry` would pass a weaker test).
local function journal_entries()
  local out = {}
  for line in io.lines(log_path) do
    if line ~= "" then
      local ok, entry = pcall(vim.json.decode, line)
      if ok then out[#out + 1] = entry end
    end
  end
  return out
end

describe("edit_commit journal entries", function()
  local notify_saved = vim.notify

  before_each(function()
    notices = {}
    vim.notify = function(msg, level) notices[#notices + 1] = { msg = msg, level = level } end
    log_path = os.tmpname()
    sql_log.set_log_path(log_path)
  end)

  after_each(function()
    vim.notify = notify_saved
    pcall(vim.fn.delete, log_path)
    clear_tabs()
  end)

  it("writes a partial commit as partial, with the reason", function()
    install_stubs(commit_body({ { affected_rows = 1 }, { affected_rows = 0 } }))
    dirty_tab()
    require("poste-db.edit_commit").commit_edits()

    local entries = journal_entries()
    assert.equals(1, #entries)
    local e = entries[1]
    assert.equals("dataset_commit", e.source)
    assert.equals("partial", e.status)
    assert.equals(1, e.affected_rows)
    assert.equals(2, e.edit_summary.updates)
    assert.truthy(e.error, "the reason text must survive into the journal")
    assert.truthy(e.error:find("1 of 2 row%(s%) affected"))
  end)

  it("warns in the notification as well as in the journal", function()
    install_stubs(commit_body({ { affected_rows = 1 }, { affected_rows = 0 } }))
    dirty_tab()
    require("poste-db.edit_commit").commit_edits()

    local last = notices[#notices]
    assert.truthy(last and last.msg:find("1 of 2 row%(s%) affected"))
    assert.equals(vim.log.levels.WARN, last.level)
  end)

  it("keeps a fully applied commit a plain success with no error text", function()
    install_stubs(commit_body({ { affected_rows = 1 }, { affected_rows = 1 } }))
    dirty_tab()
    require("poste-db.edit_commit").commit_edits()

    local entries = journal_entries()
    assert.equals(1, #entries)
    assert.equals("success", entries[1].status)
    assert.is_nil(entries[1].error)
    assert.equals(vim.log.levels.INFO, notices[#notices].level)
  end)

  it("still journals a rolled-back batch as error, not partial", function()
    install_stubs(commit_body(
      { { error = "foreign key violates", affected_rows = vim.NIL } },
      { has_error = true, rolled_back = true }))
    dirty_tab()
    require("poste-db.edit_commit").commit_edits()

    local entries = journal_entries()
    assert.equals(1, #entries)
    assert.equals("error", entries[1].status)
    assert.is_true(entries[1].rolled_back)
    assert.truthy(entries[1].error:find("foreign key violates"))
  end)
end)
